/* Assignment 1 Week - 2.
*
* Author: Rishabh Madan
* Problem: Guess the number game
* Day4 Program 10
*
*/

#include <stdio.h>  // for standard I/O operations
#include <time.h>   // for time function
#include <stdlib.h> // for rand function

int main(){
    //Generate a menu for the user
    printf("***********************************************************\n");
    printf("**----------------Welcome to Guessing Game---------------**\n");
    printf("**---------You can guess if you understand the MATH -----**\n");
    printf("**---------------------------------------------------------\n");
    printf("\n\n");

    //Declaring the basic variables and constants for the program
    const int MAX_CHANCES = 7; //stores the maximum number of chances the user can avail
    int computer_guess;        //stores the number randomly generated by the computer
    long seed = time(NULL);    //Time of the system is used as to generate the random number
    srand(seed);               //Seeding the rand()
    computer_guess = rand()%100; //generates a 2 digit random number
    int user_guess, chance_count = 1, match = 0;//Variables for the user input and game control

    // Prompt the user
    printf("Program has guessed a number, what you need to do is match it.\n");
    printf("Remember, you have only 7 chances.\n");
    printf("Best wishes...\n\n");

    while (match != 1 && chance_count <= MAX_CHANCES){
        //Taking the guess from the user
        printf("Guess the number: ");
        scanf("%d", &user_guess);

        //In case the guess made by the user is higher than the computer guess
        if (user_guess > computer_guess){
            printf("Your guess is too high\n");
            printf("Number of chances remaining: %d\n", MAX_CHANCES - chance_count);

        }

        //In case the guess made by the user is lower than the computer guess
        else if (user_guess < computer_guess){
            printf("Your guess is too low\n");
            printf("Number of chances remaining: %d\n", MAX_CHANCES - chance_count);
        }

        //If user is successful in guessing the number
        else{
            printf("Bingo!! You got it correct, %d is the number\n", computer_guess);
            printf("You guessed that in %d chances\n", chance_count);
            match = 1;
        }

    printf("\n\n");
    chance_count++;

    }

    if(match != 1)
        printf("Game over!!! Try to be mathematical.");

    else if (chance_count <= 3)
        printf("You are Super Duper NINJA!");
    else if (chance_count > 3 && chance_count <= 5)
        printf("You are Crazy NINJA!");
    else
        printf("You have potential to be a NINJA!");

    return 0;
}
